import { LogLevel } from "@sapphire/framework";
import {
	ActivityType,
	type ClientOptions,
	GatewayIntentBits,
	PresenceUpdateStatus
} from "discord.js";
import { join } from "path";

export const rootDir = join(__dirname, "..", "..");
export const srcDir = join(rootDir, "src");

export const CLIENT_OPTIONS: ClientOptions = {
	caseInsensitiveCommands: true,
	logger: {
		level: LogLevel.Debug
	},
	intents: [
		GatewayIntentBits.GuildMessages,
		GatewayIntentBits.Guilds,
		GatewayIntentBits.GuildMessages
	],
	loadMessageCommandListeners: false,
	loadDefaultErrorListeners: true,
	loadSubcommandErrorListeners: true,
	presence: {
		activities: [
			{
				name: "your thoughts",
				type: ActivityType.Listening
			}
		],
		status: PresenceUpdateStatus.Online,
		afk: false
	},
	subcommandsAdvanced: {
		nameCommandsAutogenerated: true
	}
};
