import { LogLevel } from "@sapphire/framework";
import { InternationalizationContext } from "@sapphire/plugin-i18next";
import { GatewayIntentBits, type ClientOptions } from "discord.js";
import { join } from "path";
import { getOrCreate } from "../database/guilds";

export const rootDir = join(__dirname, "..", "..");
export const srcDir = join(rootDir, "src");

export const languages = [
  {
    name: "English",
    value: "en-US",
  },
  {
    name: "Spanish",
    value: "es-ES",
  },
];

export const CLIENT_OPTIONS: ClientOptions = {
  defaultPrefix: "!",
  caseInsensitiveCommands: true,
  logger: {
    level: LogLevel.Debug,
  },
  intents: [
    GatewayIntentBits.GuildMessages,
    GatewayIntentBits.Guilds,
    GatewayIntentBits.MessageContent,
  ],
  loadMessageCommandListeners: false,
  loadDefaultErrorListeners: true,
  loadSubcommandErrorListeners: true,
  subcommandsAdvanced: {
    nameCommandsAutogenerated: true,
  },
  modules: {
    enabled: true,
  },
  i18n: {
    fetchLanguage: async (context: InternationalizationContext) => {
      if (!context.guild) return "en-US";

      const guild = await getOrCreate(context.guild.id);

      if (!guild) return "en-US";

      return guild.language;
    },
    i18next: {
      fallbackLng: "en-US",
      interpolation: {
        defaultVariables: {
          error: "❎",
          ok: "✅",
        },
      },
    },
  },
};
