import { LogLevel } from "@sapphire/framework";
import { type ClientOptions, GatewayIntentBits } from "discord.js";

export const clientConfig: ClientOptions = {
	caseInsensitiveCommands: true,
	logger: {
		level:
			process.env.NODE_ENV === "development" ? LogLevel.Debug : LogLevel.Info
	},
	intents: [
		GatewayIntentBits.GuildMessages,
		GatewayIntentBits.Guilds,
		GatewayIntentBits.GuildMessages
	],
	loadMessageCommandListeners: false,
	loadDefaultErrorListeners: true,
	loadSubcommandErrorListeners: true,
	subcommandsAdvanced: {
		nameCommandsAutogenerated: true
	}
};
